### ISSUE TITLE
Add option to filter out free weekends from the free watcher

### ISSUE THREAD

**Issue by Narcha** [dukeofsussex/SteamWatch#12]
Members of my server are not interested in free games that you can't keep, such as free weekend promotions.
It would be nice to either add a separate watcher for "free to keep" games, or to add an option to ignore free weekends in the free watcher.

**Comment by dukeofsussex** [comment]
Apologies for never responding, but this has now been implemented in v4.8.0 ❤️

**Comment by Narcha** [comment]
Sweet, thanks!
