### ISSUE TITLE
Bot keeps sending the same changelog

### ISSUE THREAD

**Issue by Rikki1408** [dukeofsussex/SteamWatch#3]
As I'm writing this issue, I just got one more ping. Now this is ridiculous, got a second one while writing!

The bot sent the same message - and another! + 1 more - update changelog message. In total, the bot has sent the same message 10 times within 3 minutes. Make that 11 now. What is going on?! 12.

Copy of the message:
:tada:[ SteamWatch 3.0 ](https://steam.watch/):tada:
Steam workshop support is finally here, along with auto-autocomp-autocomplete! Enjoy :partying_face:
:new: Added
- /search ugc: Show details for a workshop item.
- /watchers add ugc: Add a watcher for a workshop item.
- Autocomplete for watcher ids and app ids.
:pencil: Changed
- /search is now /search app
- /watchers add is now /watchers add app
- Watchers can no longer be combined (removed the "All" type). To compensate, the amount of available watchers per guild has been doubled.
- Old news posts are no longer displayed for new app watchers.
:tools: Fixed
- Fixed guilds being able to have more watchers than intended (congrats to the few guilds that got past the limit :clap:).
- Fixed <@null> being displayed in the mentions list. This is not the member you are looking for!
- Fixed <@everyone> not working.
- Fixed not being able to add watchers to announcement channels.
:wastebasket: Removed
Nothing :eyes:

And two more, this is eno - 3 more, making it 13 in total. I'm muting it temporarily until this is fixed. Yeah, change that to 16...

**Comment by Rikki1408** [comment]
I just right-clicked on the bot and gave it a 1 week timeout, however it still bypassed the timeout and sent the message again. I've kicked it for now. It was a convenient bot while it worked, and I appreciate all the work that has gone into developing it, but I'm done with it until this gets fixed.

**Comment by dukeofsussex** [comment]
@Rikki1408 I cannot apologise often enough, the combination of Discord's outage/issues and a coding mistake (now fixed in https://github.com/dukeofsussex/SteamWatch/commit/19449c953bfb6c117bfd16e8d95f564a8280a158) resulted in a wave of spam messages being sent out.

I am so very sorry for this.
